### ISSUE TITLE
Tag for releasing for MELPA Stable

### ISSUE THREAD

**Issue by furushchev** [iory/euslisp-mode#1]
as written in https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md

> To have a stable version generated for your package simply tag the repository using a naming compatible with `version-to-list`. The repo state of this tag will be used to generate the stable package.

So, please tag as current version for releasing this great package to stable repository.

Also in `euslisp-mode.el`, there are two version confused, so before releasing as tag, we should fix version with consistency.
- https://github.com/iory/euslisp-mode/blob/master/euslisp-mode.el#L6
- https://github.com/iory/euslisp-mode/blob/master/euslisp-mode.el#L13

**Comment by furushchev** [comment]
Created PR https://github.com/iory/euslisp-mode/pull/2

**Comment by iory** [comment]
Oh, Thank you!
I did not know that.
